### ISSUE TITLE
[0.0.2] Not working for me

### ISSUE THREAD

**Issue by Sythalin** [vildaberper/VRisingModding#1]
Installed through TMM, pressing Insert isn't store items, items are not sorting after being stored, etc.  Quick Stack keybind is showing up in the options, so mod is being loaded; It's just not doing anything.

Other mods installed are working fine (ModernCamera, PopupTotals, etc.).

EDIT: Also verified the config, said features are set to "true".

**Comment by vildaberper** [comment]
I'm pretty sure you only installed the mod on the client. Try installing [ServerLaunchFix](https://v-rising.thunderstore.io/package/Mythic/ServerLaunchFix/) as well. You could also install BepInEx, Wetstone and PPRising manually in VRising\VRising_Server\BepInEx.

**Comment by vildaberper** [comment]
I should probably add some kind of warning for this.

**Comment by Sythalin** [comment]
Installed ServerLaunchFix and working as intended.  Thanks!

**Comment by vildaberper** [comment]
Nice. I'll keep this open until there is some kind of warning for missing plugin / version mismatch between server and client.

**Comment by Kydoimos97** [comment]
Thank you for the great mod, just a quick suggestion on this topic. It might help if you put a reference to this issue and its fix in the thunderstore page description of the mod? It's an easy and faster fix for now than a warning would be.

**Comment by vildaberper** [comment]
That is probably a a better idea. I'll update the docs. Thank you for the input!
