### ISSUE TITLE
Client Crash (v0.0.3)

### ISSUE THREAD

**Issue by crunchprank** [vildaberper/VRisingModding#3]
My client crashed when pressing the `insert` button to perform the quick stack function. My configuration file is untouched. The log itself was rather long, so I have pasted it to PasteBin below:

https://pastebin.com/raw/xemnQMaQ

It mentions at the end for possible stack traces, check `AppData/Local/Temp/Stunlock Studios/VRising/Crashes` but that directory doesn't seem to exist. Let me know if you need any additional details.

**Comment by vildaberper** [comment]
What other plugins do you have installed? And what versions?

**Comment by crunchprank** [comment]
Latest version of the game. Plugins are below:

```
BepInEx-BepInExPack_V_Rising-1.0.0
molenzwiebel-Wetstone-1.1.0
Nightbreak-PopupTotals-1.0.5
vrising-ModernCamera-1.3.1
PP-PPRising-0.0.3
```

**Comment by vildaberper** [comment]
Does it work with ModernCamera disabled/removed?

**Comment by crunchprank** [comment]
I can't say for sure right now but I can do some testing and will report back.

**Comment by vildaberper** [comment]
Any update on this? I've tried the updated versions of stated mods but stacking with the hotkey does not crash my client.

**Comment by crunchprank** [comment]
No update at this time. I'll go ahead and close this out for now.
