### ISSUE TITLE
[SUGGESTION] Console command

### ISSUE THREAD

**Issue by WtfShipoopi** [vildaberper/VRisingModding#4]
To make it so that people do not have to download a client-side, pull a command from the console. The game allows for binds to be created. So a simple !pprise in the console would compulsively count.

Then people only have to do something along the lines of   'console.bInd Shift+KeypadPlus !pprise'
Allowing people to be able to use the mod without having to install the addon client side.

**Comment by vildaberper** [comment]
That is a really good idea! Thank you for the suggestion.

**Comment by vildaberper** [comment]
The in-game console is sadly client-side - so there is no way to implement this. I hope this will change in the future as it would enable a lot of cool stuff for vanilla clients.
Next update will include a chat command for quick stacking (defined in in config, default "!qs"). This is the best I can do for now...
